module.exports =
[
  {
    id:'bitcoin',//
    symbol:'BTC',
    port:9334,
    img:'/img/bitcoin.png',
    server:'sha256.p2p-spb.xyz:'
  },
  {
    id:'binance-peg-litecoin',//
    symbol:'LTC',
    port:9327,
    img:'/img/ltc.png',
    server:'p2p-spb.xyz:'
  },
  {
    id:'dash',//
    symbol:'DASH',
    port:7903,
    img:'/img/dash.png',
    server:'p2p-spb.xyz:'
  },
  {
    id:'bitcoin-cash',//
    symbol:'BCH',
    port:9338,
    img:'/img/bch.png',
    server:'sha256.p2p-spb.xyz:'
  },
  {
    id:'bitcoin-cash-sv',
    symbol:'BSV',
    port:6339,
    img:'/img/bsv.png',
    server:'sha256.p2p-spb.xyz:'
  },
    {
    id:'ecash',//
    symbol:'XEC',
    port:9340,
    img:'/img/ecash.png',
    server:'sha256.p2p-spb.xyz:'
  },
   {
    id:'bitcoin-atom',
    symbol:'BCA',
    port:3027,
    img:'/img/atom.png',
    server:'sha256.p2p-spb.xyz:'
  },
  {
    id:'none',
    symbol:'RUBTC',
    port:6353,
    img:'/img/rubtc.png',
    server:'sha256.p2p-spb.xyz:'
  },
  {
    id:'monacoin',//
    symbol:'MONA',
    port:2942,
    img:'/img/monacoin.png',
    server:'p2p-spb.xyz:'
  },
  {
    id:'dogecoin',//
    symbol:'DOGE',
    port:4556,
    img:'/img/doge.png',
    server:'p2p-spb.xyz:'
  },
   {
    id:'flourmix',//
    symbol:'FLO',
    port:5210,
    img:'/img/flo.png',
    server:'p2p-spb.xyz:'
  },
  {
    id:'einsteinium',//
    symbol:'EMC2',
    port:3039,
    img:'/img/emc2.png',
    server:'p2p-spb.xyz:'
  },
  {
    id:'goldcoin',//
    symbol:'GLC',
    port:8124,
    img:'/img/goldcoin.png',
    server:'p2p-spb.xyz:'
  },
  {
    id:'axe',//
    symbol:'AXE',
    port:7923,
    img:'/img/axe.png',
    server:'p2p-spb.xyz:'
  },
  {
    id:'cannabiscoin',//
    symbol:'CANN',
    port:28741,
    img:'/img/cann.png',
    server:'p2p-spb.xyz:'
  },
   {
    id:'bitcore',//
    symbol:'BTX',
    port:3017,
    img:'/img/bitcore.png',
    server:'p2p-spb.xyz:'
  },
 {
    id:'garlicoin',//
    symbol:'GRLC',
    port:5213,
    img:'/img/garli.png',
    server:'p2p-spb.xyz:'
  },
  {
    id:'vertcoin',//
    symbol:'VTC',
    port:9171,
    img:'/img/vtc.png',
    server:'p2p-spb.xyz:'
  },
  {
    id:'avian-network',//
    symbol:'AVN(x16rt)',
    port:16106,
    img:'/img/avn.png',
    server:'p2p-spb.xyz:'
  },
  {
    id:'avian-network',//
    symbol:'AVN(minotaurX)',
    port:16106,
    img:'/img/avn.png',
    server:'p2p-spb.xyz:'
  },
  {
    id:'litecoin-cash',//
    symbol:'LCC(sha256)',
    port:5555,
    img:'/img/lcc.png',
    server:'sha256.p2p-spb.xyz:'
  },
  {
    id:'litecoin-cash',//
    symbol:'LCC(minotaurX)',
    port:5557,
    img:'/img/lcc.png',
    server:'p2p-spb.xyz:'
  },
  {
    id:'auroracoin',//
    symbol:'AUR(sha256)',
    port:12349,
    img:'/img/aurora.png',
    server:'sha256.p2p-spb.xyz:'
  },
  {
    id:'auroracoin',//
    symbol:'AUR(qubit)',
    port:12355,
    img:'/img/aurora.png',
    server:'p2p-spb.xyz:'
  },
  {
    id:'auroracoin',//
    symbol:'AUR(scrypt)',
    port:12347,
    img:'/img/aurora.png',
    server:'p2p-spb.xyz:'
  },
  {
    id:'auroracoin',//
    symbol:'AUR(groestl)',
    port:12351,
    img:'/img/aurora.png',
    server:'p2p-spb.xyz:'
  },
  {
    id:'auroracoin',//
    symbol:'AUR(skein)',
    port:12353,
    img:'/img/aurora.png',
    server:'p2p-spb.xyz:'
  },
  {
    id:'digibyte',//
    symbol:'DGB(sha256)',
    port:5027,
    img:'/img/dgb.png',
    server:'sha256.p2p-spb.xyz:'
  },
  {
    id:'digibyte',//
    symbol:'DGB(qubit)',
    port:5023,
    img:'/img/dgb.png',
    server:'p2p-spb.xyz:'
  },
  {
    id:'digibyte',//
    symbol:'DGB(scrypt)',
    port:5025,
    img:'/img/dgb.png',
    server:'p2p-spb.xyz:'
  },
  {
    id:'digibyte',//
    symbol:'DGB(skein)',
    port:5029,
    img:'/img/dgb.png',
    server:'p2p-spb.xyz:'
  },
  {
    id:'digibyte',///
    symbol:'DGB(odo)',
    port:5031,
    img:'/img/dgb.png',
    server:'p2p-spb.xyz:'
  },  
  {
    id:'myriadcoin',//
    symbol:'XMY(argon2d)',
    port:6002,
    img:'/img/myr.png',
    server:'p2p-spb.xyz:'
  },
  
]
